### ISSUE TITLE
쿠폰 관련 기본 기능 개발

### ISSUE THREAD

**Issue by znftm97** [znftm97/coupon_platform#1]
### Description
설계한 요구사항(기능)들을 구현하기 전에, 필요한 기본 기능들을 개발한다.
개발에 필요한 예외처리, API 포맷 등과 같은 공통적인 처리도 포함한다.
- 설계한 요구사항(기능)들에 집중하기위해, 간단한 기본 기능들에 대한 테스트코드는 생략

### To-Be
- 쿠폰을 생성할 수 있다.
- 쿠폰 발급할 수 있다.
- 쿠폰을 조회할 수 있다.
- 모든 API는 같은 응답 포맷을 가진다.
- 예외가 발생해도, 정의한 응답 포맷으로 응답할 수 있다.

### Todo
- [x] 도메인 객체 생성
- [x] API 응답 포맷 정의
- [x] 글로벌 예외처리
- [x] 쿠폰 생성 API
- [x] 쿠폰 발급 API
- [x] 쿠폰 조회 API
