### ISSUE TITLE
N일 연속 출석체크 이벤트 기능 구현

### ISSUE THREAD

**Issue by znftm97** [znftm97/coupon_platform#14]
### 요구사항
1. **연속 출석체크시 쿠폰을 발급한다.**
    - 3일 연속 출석체크시 `3일 연속 출석체크 1000원 쿠폰` 발급
    - 7일 연속 출석체크시 `7일 연속 출석체크 5000원 쿠폰` 발급
    - 30일 연속 출석체크시 `30일 연속 출석체크 50000원 쿠폰` 발급
2. **로그인하면 출석체크된다고 가정하지만, 로그인 기능은 구현하지 않는다.**
    - 로그인 기능을 대신할 임시 API를 통해 출석체크 기능을 구현한다.
3. **출석체크 쿠폰 발급 이벤트 기간동안에는, 계속해서 참여할 수 있다.**
    - 예로 4일 연속 출석체크 후, 5일째 출석체크를 하지 않고, 6일째 다시 출석체크를 하는경우
    처음부터 다시 출석체크 이벤트에  참여하게 된다.
4. **각 쿠폰은 중복 발급되지 않는다.**
    - 예로 6일 연속 출석체크해도, `3일 연속 출석체크 쿠폰`은 3일째 한번만 발급된다.
    - 단, 연속성이 깨지면 즉 처음부터(1일차) 다시 출석체크를 하는 경우에는 쿠폰이 발급된다.
5. **애플리케이션 서버는 여러개로, 분산 환경이라고 가정한다.**
6. **해당 서비스에 가입한 사용자 수는 천만명이라고 가정한다.**

## Todo
- [x] 로그인 대체 임시 API 추가
- [x] 배치 모듈 추가
- [x] 배치 로직 작성
- [x] 테스트 코드 작성
