### ISSUE TITLE
검색어 자동완성 기능 구현

### ISSUE THREAD

**Issue by znftm97** [znftm97/coupon_platform#16]
### Description
검색어 입력시, 관련된 검색어 5개를 노출한다.
검색어 자동 완성 기능 구현을 위해, 쿠폰 이름을 통한 검색 기능을 함께 구현한다.

### To-Be
- 쿠폰 이름을 통해, 쿠폰을 검색할 수 있다.
- 관련된 쿠폰의 이름이 최대 5개 자동완성되어 반환된다. 

### Todo
- [ ] 쿠폰 검색 기능 구현
- [ ] 검색어 자동완성 기능 구현
- [ ] 테스트 코드 작성
