### ISSUE TITLE
통계 기능 구현

### ISSUE THREAD

**Issue by znftm97** [znftm97/coupon_platform#21]
### Description
쿠폰 시스템 개선을 위해, 쿠폰 관련 통계 데이터를 산출하라는 업무가 주어졌다고 가정해보자.
이 데이터는 화면을 통해 제공될 예정이고, 사내 구성원이 사용하는 어드민 서비스에 노출된다.

1. **통계 데이터**
    1. 쿠폰 발급 개수
    2. 쿠폰 사용 개수
    3. 기간이 만료된 쿠폰 개수
    4. 발급된 쿠폰들 기준으로, 쿠폰 사용 비율
    5. 조회한 데이터의, a ~ d 항목 합계 및 평균 데이터
2. **통계 데이터의 날짜 범위는, 클라이언트의 요청에 포함된 날짜를 기준으로 한다.**
    - 날짜 범위는 클라이언트에서 자유롭게 직접 지정할 수 있다.
    - 유효하지 않은 날짜 데이터는 인입되지 않는다고 가정한다. (validation 생략)
3. **통계 데이터는 하루마다 갱신된다.**
    - 오늘이 2023-10-13일 이라면, 2023-10-12일 까지 데이터만 조회할 수 있다.
4. **생성된 쿠폰의 개수는 1억개라고 가정한다.**

### 예시
<html>
<body>

날짜 | 쿠폰 발급 개수 | 쿠폰 사용 개수 | 기간이 만료된 쿠폰 개수 | 쿠폰 사용 비율(%)
-- | -- | -- | -- | --
2023-10-15 | 1 | 1 | 0 | 100
2023-10-16 | 10 | 5 | 1 | 50
2023-10-17 | 1 | 0 | 0 | 0
합계 | 12 | 6 | 1 | 50

### rest-assured 라이브러리 적용
시나리오 테이스트에 rest-assured를 적용한다.

</body>
</html>

### To-Be
- 쿠폰 관련 통계 데이터를 계산할 수 있다.

### Todo
- [ ] 통계 데이터 조회 API
- [ ] 통계 테스트 코드 작성
- [ ] 기존 시나리오 테스트 rest-assured 적용
