### ISSUE TITLE
쿠폰 코드를 통한 쿠폰 발급 기능

### ISSUE THREAD

**Issue by znftm97** [znftm97/coupon_platform#7]
### Description
쿠폰 코드를 입력하면, 쿠폰을 발급받는 기능을 구현한다.
또한 각 엔티티의 external_id, 요청 트래킹 id에서 난수를 필요로 하므로, 이를 함께 고려해서 구현한다.
이에 대한 요구사항, 설계, 기술 선택 과정은 노션 링크를 남긴다.
- https://www.notion.so/6f5ee3a7208d4db3a7d42facfd8d814c

### To-Be
- 쿠폰 코드를 통해, 쿠폰을 발급받을 수 있다.
- 쿠폰 코드를 생성하는 기술이 변경되어도 사이드 이펙트를 최소화 된다. 

### Todo
- [ ] 쿠폰 코드 엔티티 및 테이블 생성
- [ ] 난수 생성 객체 설계 및 구현
- [ ] MDC 로그백 설정
- [ ] 난수 생성 단위 테스트 코드 작성
- [ ] 쿠폰 코드로 쿠폰 발급 단위 테스트 코드 작성
